### ISSUE TITLE
Right clicking and clicking away on the program icon causes the program to close.

### ISSUE THREAD

**Issue by abdelrahman-aboelnour** [josetr/AudioDeviceSwitcher#2]
First of all thanks alot for this program, it makes life WAY easier for me since I have to constantly switch between speaker,rear mic to headphones/front mic.

one small bug if I right-click on the program in the taskbar then click away, the program closes. it is a tiny issue but sometimes causes accidental closing of the program and the shortcuts not working. will be great if this is fixed and an option to toggle that icon off is available, thanks alot for the effort <3

**Comment by abdelrahman-aboelnour** [comment]
https://user-images.githubusercontent.com/77008017/146678262-d5b920ec-dcc2-4437-8bc3-f0aab291c9ef.mp4

screen recording of what I mean ^

**Comment by josetr** [comment]
I'm really glad you found it useful!

As for the issue, I've already fixed it but it usually takes a few days for Microsoft to validate, approve and publish the update. I'll let you know when it's ready.

**Comment by josetr** [comment]
The update is now available. I hope it works well.
